### ISSUE TITLE
Create the LandingPage theme.

### ISSUE THREAD

**Issue by rohitkrishna094** [open-source-developers/front-end#14]
#### What is this?

- Feature - use branch named `feature/landing-page` to finish this feature.

#### Explain in detail if needed:
Create the theme (i.e., only html and css) for the landing page. Follow the image below and add your own take on it if needed, since wireframes haven't been decided yet. The key takeaway is the two column layout as shown below.

![2](https://user-images.githubusercontent.com/18495886/63288688-50010e80-c28b-11e9-88d0-4e9fbed1868c.png)

You can also check [Material UI](https://material-ui.com/getting-started/templates/sign-in-side/) website for similar inspiration.

For mobile, use this as an inspiration.

![4](https://user-images.githubusercontent.com/18495886/63288813-9d7d7b80-c28b-11e9-8d19-0f9c4b715166.png)

Functionality to be followed in next issue.

**Comment by emon535** [comment]
yes please.

Foysal Ahmed Emon
Software Engineer at Infolytx
Phone : +8801520100178
Linkedin: https://linkedin.com/in/emon535/
<https://www.linkedin.com/in/emon535/>

**Comment by 404kacper** [comment]
Sounds good 👍
