### ISSUE TITLE
Create the Profile Page (Component only)

### ISSUE THREAD

**Issue by rohitkrishna094** [open-source-developers/front-end#15]
#### What is this?

- Feature - use branch named `feature/profile-page` to finish this feature.

#### Explain in detail if needed:
Create a new component under `components` folder and name it `Profile`. Use react-router to route to this component when the route is `/profile`. Don't worry about authorization or other aspects. Just create an empty component that just display a header saying `Profile works`

**Comment by emon535** [comment]
Can I take the task?

**Comment by rohitkrishna094** [comment]
@emon535 Sure.

**Comment by rohitkrishna094** [comment]
@emon535 I have updated the description and have added a site which has decent templates for profile page. You can take a look at them for inspiration. However if you have a better template you can use it as well or you can mix and match between this and your templates if you want.

**Comment by rohitkrishna094** [comment]
@emon535 I am taking this now. We will add more issues for profile page theme itself which you can work on if you are interested. :D
