### ISSUE TITLE
Protected Routing

### ISSUE THREAD

**Issue by 404kacper** [open-source-developers/front-end#18]
**Is your feature request related to a problem? Please describe.**
We will start working on routing in this project, for that we need protected and basic routes.

**Describe the solution you'd like**
Create a `routing` folder inside `components` directory with `PrivateRoute.jsx` component and `Routes.jsx` component. You should be able to essentialy replace `<Route/>` declaration with `<PrivateRoute />` component that you've created before and have it redirect you to appropriate component based on whether you're authenticated or not. For now use component level state that will hold two values: `authenticated:` and `loading:` both of them set to false by default.

**Describe alternatives you've considered**
We might want to wait for profile routes to be set-up first.

## Pull Request Squashing
Please, go through these steps before you submit a PR.

1. Make sure that your PR is not a duplicate.
2. If not, then make sure that:

  2.1. You have done your changes in a separate branch. Branches MUST have descriptive names that start with either the `fix/` or `feature/` prefixes. Good examples are: `fix/signin-issue` or `feature/issue-templates`.

  2.2. You have a descriptive commit message with a short title (first line).

  2.3. You have only one commit (if not, squash them into one commit).

  2.4. `npm test` doesn't throw any error. If it does, fix them first and amend your commit (`git commit --amend`).

3. **After** these steps, you're ready to open a pull request.

  3.1. Give a descriptive title to your PR.

  3.2. Provide a description of your changes.

  3.3. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

**Comment by rohitkrishna094** [comment]
I am taking this. is it ok?
