### ISSUE TITLE
Create a Navbar folder and Navbar.jsx file

### ISSUE THREAD

**Issue by rohitkrishna094** [open-source-developers/front-end#26]
**Is your feature request related to a problem? Please describe.**
We need a new folder and a new file before working on actual Navbar theme.

**Describe the solution you'd like**
1) Create a new folder inside components folder and call it `Navbar`
2) Inside this folder, create a file called `Navbar.jsx` which is a React component.
3) Make sure that this react component is a functional component and render this `<h1>Navbar works</h1>`

You can work on this feature using a branch called `feature/navbar-component`.

## Pull Request Squashing
Please, go through these steps before you submit a PR.

1. Make sure that your PR is not a duplicate.
2. If not, then make sure that:

  2.1. You have done your changes in a separate branch. Branches MUST have descriptive names that start with either the `fix/` or `feature/` prefixes. Good examples are: `fix/signin-issue` or `feature/issue-templates`.

  2.2. You have a descriptive commit message with a short title (first line).

  2.3. You have only one commit (if not, squash them into one commit).

  2.4. `npm test` doesn't throw any error. If it does, fix them first and amend your commit (`git commit --amend`).

3. **After** these steps, you're ready to open a pull request.

  3.1. Give a descriptive title to your PR.

  3.2. Provide a description of your changes.

  3.3. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

**Comment by KristianWEB** [comment]
Created folder named Navbar and a React Component named NavBar.jsx. I've registered the component in the routes in case you want to see it. Sending Pull Request.
