### ISSUE TITLE
Create Navbar UI

### ISSUE THREAD

**Issue by rohitkrishna094** [open-source-developers/front-end#27]
**Is your feature request related to a problem? Please describe.**

***Note: Once Issue #26 is closed, only then should you work on this issue.*** 

We need to make Navbar UI for desktops. Don't worry about making it mobile responsive. But make sure that its responsive on all desktop or ipad resolutions.

**Describe the solution you'd like**
In this issue, you are supposed to write html, css code for Navbar component. This component is in `components/Navbar/Navbar.jsx`. For css, you can add another file in this path `components/Navbar/Navbar.css` and then import it in `Navbar.jsx`. Use ant-design wherever possible.

**Helpers**
Use the below UI template for inspiration. However if you have a better template, please do bring it up in discussion on our discord channel.

https://html.crumina.net/html-olympus/02-ProfilePage.html

The Navbar is at the top of the above webpage.

You can work on this feature using a branch called `feature/navbar-component`.

## Pull Request Squashing
Please, go through these steps before you submit a PR.

1. Make sure that your PR is not a duplicate.
2. If not, then make sure that:

  2.1. You have done your changes in a separate branch. Branches MUST have descriptive names that start with either the `fix/` or `feature/` prefixes. Good examples are: `fix/signin-issue` or `feature/issue-templates`.

  2.2. You have a descriptive commit message with a short title (first line).

  2.3. You have only one commit (if not, squash them into one commit).

  2.4. `npm test` doesn't throw any error. If it does, fix them first and amend your commit (`git commit --amend`).

3. **After** these steps, you're ready to open a pull request.

  3.1. Give a descriptive title to your PR.

  3.2. Provide a description of your changes.

  3.3. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

**Comment by KristianWEB** [comment]
Created non-responsive NavBar component for now. Sending Pull Request.

**Comment by 404kacper** [comment]
Shall we close this issue and create new one for responsive navbar? Or do we keep this one open.

**Comment by KristianWEB** [comment]
I'm going to now modify the UI design of the Navbar component and then implement it on top of our existing React UI component.

**Comment by KristianWEB** [comment]
Closing this issue and will open a new one because I'm going to use styled-components.
