### ISSUE TITLE
Travis not working with heroku 

### ISSUE THREAD

**Issue by rohitkrishna094** [open-source-developers/front-end#36]
**Describe the bug**
Change the `travis.yml` so that once the lint, build steps are done, the frontend react app should be deployed to heroku. Use your personal account, but add the api key as environment variable. 

Note: I tried for travis.com, not travis.org. Lets stick with travis.com as I believe travis.org is old and will/should be deprecated in the future according to [stackoverflow](https://devops.stackexchange.com/questions/1201/whats-the-difference-between-travis-ci-org-and-travis-ci-com)

**Steps:**
Here is what I've tried and it may help you.

1. Check [travis tutorial](https://docs.travis-ci.com/user/deployment/heroku/)
2. Do `heroku login` in your CLI.
3. You might have to run `travis encrypt $(heroku auth:token) --add deploy.api_key --pro`
4. Now you will see that the above command has added an api token in `.travis.yml` file. Copy this and add it as env variable(with `heroku_token` as the key and token as the value) in travis.com website for frontend repo. And in `.travis.yml` file replace the token with something like `$heroku_token`. You can learn more about env variables [https://docs.travis-ci.com/user/environment-variables/]()

**Comment by 404kacper** [comment]
This issue should’ve been resolved by now along with some minor fixes.
