### ISSUE TITLE
Register Credentials not removed after registering

### ISSUE THREAD

**Issue by rohitkrishna094** [open-source-developers/front-end#42]
**Describe the bug**
In the landing page, once someone has registered, their credentials are still in input boxes. We need to clear that state. Also when someone has registered, we should not only show a message saying `Registration successful`(which we are doing now), but should also point them to `login tab`.

**Screenshots**
Here is the screenshot. Look at the top, it says registration successful, but the credentials with which I have registered are still in the input boxes.

![Untitled](https://user-images.githubusercontent.com/18495886/63989067-efed4200-caac-11e9-81b9-df216d31cb8e.png)

**Summary**
1) Clear the state once someone has registered successfully.
2) Show the message saying that they have registered successfully(which we are already doing, so don't remove this)
3) Now point them to `login tab`.

**Comment by 404kacper** [comment]
Credentials are now removed on successful request

**Comment by 404kacper** [comment]
Closing the issue since user is now getting automatically redirected when registered.
