### ISSUE TITLE
Login and register should work with enter button

### ISSUE THREAD

**Issue by rohitkrishna094** [open-source-developers/front-end#46]
**Describe the bug**
When user enters their credentials on login or register page, they shouldn't have to press the button with mouse to login or register. They should be able to do so by directly hitting the `enter` key or `return` key on their keyboard.

**Possible Solution**
You might have to look into `onkeydown` and see if the key pressed is the enter key.

**Additional Notes**
Use a branch called `bug/enter-submit` or something to work on this issue.

**Comment by KristianWEB** [comment]
@rohitkrishna094 I'm currently working on the issue and I'm having difficulties testing the login authentication functionality locally. How do I set it up so it works on my PC?

**Comment by KristianWEB** [comment]
Nevermind everything is fine now.

**Comment by KristianWEB** [comment]
Fixed the bug and now the user can directly login/register by hitting the `enter/return` key, Sending PR.

**Comment by 404kacper** [comment]
This issue was resolved by commit #48 so I’m closing it.
