### ISSUE TITLE
Add form validation for password input

### ISSUE THREAD

**Issue by williamj1788** [open-source-developers/front-end#56]
**Is your feature request related to a problem? Please describe.**
As it stands there's no validation for the password input on the registration form.
You can enter "1" for a password and that would be considered valid.
Short passwords are a security risk because they are easier to brute force.

**Describe the solution you'd like**
If the password is too small (Ex: less than 6 characters) then a message should appear saying so.

**Describe alternatives you've considered**
You could also have more validation like:
* Must have one capital letter
* Must have one number

You don't have to use all or any of these but there are just some examples, but there has to be a balance between security and convenience. No likes going through multiple hoops just a make a password.

## Pull Request Squashing
Please, go through these steps before you submit a PR.

1. Make sure that your PR is not a duplicate.
2. If not, then make sure that:

  2.1. You have done your changes in a separate branch. Branches MUST have descriptive names that start with either the `fix/` or `feature/` prefixes. Good examples are: `fix/signin-issue` or `feature/issue-templates`.

  2.2. You have a descriptive commit message with a short title (first line).

  2.3. You have only one commit (if not, squash them into one commit).

  2.4. `npm test` doesn't throw any error. If it does, fix them first and amend your commit (`git commit --amend`).

3. **After** these steps, you're ready to open a pull request.

  3.1. Give a descriptive title to your PR.

  3.2. Provide a description of your changes.

  3.3. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

**Comment by rohitkrishna094** [comment]
Do you recommend a library for this on frontend?

**Comment by williamj1788** [comment]
I mean personally I would prefer that you come with a non-external-library solution because having another library makes the project harder to understand without having to read more documentation. 
But whatever works is ok.
