### ISSUE TITLE
Refactor landing page forms to be separate components

### ISSUE THREAD

**Issue by williamj1788** [open-source-developers/front-end#58]
**Is your feature request related to a problem? Please describe.**
The Landing Page has 2 forms. Each has its own separate state and submit functions.
The Separation of concerns principle tells us that these form should be in there own component/file. 

**Describe the solution you'd like**
Create a component called LoginForm and put it in its own file. It will contain all the state and logic of the login form. Do the same for the registration form but called it RegistrationForm.

Both components must share the same isPending state. You can have the LandingPage component have the pending state and give the forms props that allow them to read/set it or you can use the Context API.

Either way, there should be NO VISUAL DIFFERENCE between the old and the new landing page.

## Pull Request Squashing
Please, go through these steps before you submit a PR.

1. Make sure that your PR is not a duplicate.
2. If not, then make sure that:

  2.1. You have done your changes in a separate branch. Branches MUST have descriptive names that start with either the `fix/` or `feature/` prefixes. Good examples are: `fix/signin-issue` or `feature/issue-templates`.

  2.2. You have a descriptive commit message with a short title (first line).

  2.3. You have only one commit (if not, squash them into one commit).

  2.4. `npm test` doesn't throw any error. If it does, fix them first and amend your commit (`git commit --amend`).

3. **After** these steps, you're ready to open a pull request.

  3.1. Give a descriptive title to your PR.

  3.2. Provide a description of your changes.

  3.3. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

**Comment by 404kacper** [comment]
I'm down for the idea of separating LandingPage.jsx though i'm not really foud of separating auth state.
Clearing up components should be enough to increase readability.
