### ISSUE TITLE
Design Navbar UI component, implement the design using React and styled-components

### ISSUE THREAD

**Issue by KristianWEB** [open-source-developers/front-end#72]
**Is your feature request related to a problem? Please describe.**

We currently have a mocked-up Navbar React component but we need to redesign it according to olympus design and implement the new design. The Navbar Component should be fully responsive using the mobile-first approach and the minimum mobile resolution for responsiveness should be `> 320-365px `

**Describe the solution you'd like**
In this issue, you are supposed to write html, css code for Navbar component. This component is in `components/Navbar/Navbar.jsx`. For css, you can use `styled-components` and then import them into `Navbar.jsx`. Use `ant-design` wherever possible.

**Helpers**
Use the below UI Design ( Dev's logo is being used as we don't have one for the app ): 
`365px ( Iphone XR/XS ) : 715px`

![365px](https://user-images.githubusercontent.com/46797006/65723666-87977d80-e0b7-11e9-8580-88f53b25ed31.PNG)

`765px : 1000px`

![765px - 1000px](https://user-images.githubusercontent.com/46797006/65725632-cf200880-e0bb-11e9-8c33-f6e0287deb66.PNG)

`1000px+`

![1000px+](https://user-images.githubusercontent.com/46797006/65725951-87e64780-e0bc-11e9-896c-2caf4c50ed49.PNG)

### The Navbar component is tight coupled with the Sidebar ( the pages navigation sit in there ) Here's the design: 
![1](https://user-images.githubusercontent.com/46797006/65642148-3fb12180-dff7-11e9-9101-153be4c09f0e.PNG)
Tho this Sidebar is going to be discussed on other issue, just to let you know that those two components work together.

You can work on this feature using a branch called `feature/navbar-component`.

## Pull Request Squashing
Please, go through these steps before you submit a PR.

1. Make sure that your PR is not a duplicate.
2. If not, then make sure that:

  2.1. You have done your changes in a separate branch. Branches MUST have descriptive names that start with either the `fix/` or `feature/` prefixes. Good examples are: `fix/signin-issue` or `feature/issue-templates`.

  2.2. You have a descriptive commit message with a short title (first line).

  2.3. You have only one commit (if not, squash them into one commit).

  2.4. `yarn test` doesn't throw any error. If it does, fix them first and amend your commit (`git commit --amend`).

3. **After** these steps, you're ready to open a pull request.

  3.1. Give a descriptive title to your PR.

  3.2. Provide a description of your changes.

  3.3. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

**Comment by rohitkrishna094** [comment]
Here are some questions regarding this navbar

1) In phone view, how to access user settings? Like will it in sidebar? If so how to trigger that sidebar? There is no hamburger icon or similar in it?
2) In 715px and 1000px, would it be better to include the dropdown arrow beside user picture since the user settings will be there in the drop down menu?

**Comment by KristianWEB** [comment]
1. My intention was to open the sidebar when you click on the logo but that would actually be really weird as it should point to the homepage. Will add a hamburger menu right of the search bar.

2. That's a good idea, will implement that aswell.

**Comment by KristianWEB** [comment]
Updated the navbar component's design, now about to start implementing it.
