### ISSUE TITLE
Redux auth implementation 

### ISSUE THREAD

**Issue by 404kacper** [open-source-developers/front-end#79]
**Is your feature request related to a problem? Please describe.**
For now the auth is working, except there are few things that are yet to be implemented:

- ~~Error handling in catch~~
- ~~Deleting old context structure (Do it only when other points are ticked out, the old context structure should stay for now as a reference)~~
- ~~Remembering the user - storing the data in session storage or storing the data in local storage if user ticks out "remember me" option on UI.~~
- ~~Message display on both unsuccessful and successful response~~
- ~~Front end input validation~~
- ~~Lint fixes~~

When you're done with one of the features tick them out like so: 

~~feature~~

## Pull Request Squashing
Please, go through these steps before you submit a PR.

1. Make sure that your PR is not a duplicate.
2. If not, then make sure that:

  2.1. You have done your changes in a separate branch. Branches MUST have descriptive names that start with either the `fix/` or `feature/` prefixes. Good examples are: `fix/signin-issue` or `feature/issue-templates`.

  2.2. You have a descriptive commit message with a short title (first line).

  2.3. You have only one commit (if not, squash them into one commit).

  2.4. `npm test` doesn't throw any error. If it does, fix them first and amend your commit (`git commit --amend`).

3. **After** these steps, you're ready to open a pull request.

  3.1. Give a descriptive title to your PR.

  3.2. Provide a description of your changes.

  3.3. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

**Comment by KristianWEB** [comment]
@404kacper All the issues are now fixed, review the commits I've made and then I'll merge the PR.

**Comment by 404kacper** [comment]
The implementation is throwing errors when user tries to register a already existing account (eg. same email as in database).

**Comment by KristianWEB** [comment]
Yeah you are right. I'll fix those issues and make a new commit.

**Comment by KristianWEB** [comment]
Fixed the register issue and added the remember variable into redux's state. However I'm still checking on the payload whether I should put the JWT token into sessionStorage or localStorage simply because the payload is adding remember's actual value into the reducer. Correct me if I'm wrong.
