### ISSUE TITLE
Initial setup for posting

### ISSUE THREAD

**Issue by 404kacper** [open-source-developers/front-end#83]
**Is your feature request related to a problem? Please describe.**
We're starting off with the posting, for most part back-end is set-up and now we must focus on implementing it within front-end repo. For starters you should create:
- A reducer named **post** and connect it to redux.
- An action file named **post**.
- Two types: **ADD_POST**(will be dispatched in try part of action) and **POST_ERROR**(will be dispatched in catch part of action).
- Posting directory where all of the post components should be held src-->app-->components-->ProfilePage-->components-->Posting
- Parent component named **post.jsx**, which is already has it's static holder in "**CreatePost**" component.
- The post component should have an **addPost** action that's simply adding the post to our DB. The base URI for posting is: **https://osd-sidekick.herokuapp.com/api/posts**, to create a post you must send a POST request to our back end via above URI with appropriate headers.
These headers are: 
- Authorization with jwt token that's stored in local or session storage based what user choosed.
- Content-Type of application/json
For the request body you should only send the **content** document query.
The content value is what user inputs in post form if you don't know how to read and store strings from input you should look into auth component where login and password fields were and how they worked (this must be a component level state).
To validate whether data was successfully store in db you must check the cluster on our remote mongoDB, if you're not yet added there ask any of the active contributors to send you an invite.

**Describe the solution you'd like**
For now your component should only store data in db after clicking the publish button, you're not required to display the newly added post yet.

## Pull Request Squashing
Please, go through these steps before you submit a PR.

1. Make sure that your PR is not a duplicate.
2. If not, then make sure that:

  2.1. You have done your changes in a separate branch. Branches MUST have descriptive names that start with either the `fix/` or `feature/` prefixes. Good examples are: `fix/signin-issue` or `feature/issue-templates`.

  2.2. You have a descriptive commit message with a short title (first line).

  2.3. You have only one commit (if not, squash them into one commit).

  2.4. `npm test` doesn't throw any error. If it does, fix them first and amend your commit (`git commit --amend`).

3. **After** these steps, you're ready to open a pull request.

  3.1. Give a descriptive title to your PR.

  3.2. Provide a description of your changes.

  3.3. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

**Comment by KristianWEB** [comment]
Implemented all the features requested in the issue, closing issue..
